Moving
rose-projects/SwARM pull request #25
Opened 2017-01-22 23:46 UTC by AlbandeCrevoisier

Add algorithm which allows an arrival orientation to be set

2017-01-23 10:18 UTC, superpingu reviewed
j'ai pas fini mais voilà

2017-01-23 10:18 UTC, superpingu commented on robot/coding_wheels.c
> +}
euh, c'est quoi tout ça ?

2017-01-23 10:18 UTC, superpingu commented on robot/exticonf.c
> +
Dafuk ? c'est pas déjà déclaré ça ? A mon avis faut virer coding_wheels.c et le .h , met les extern dans exticonf.h

2017-01-23 10:18 UTC, superpingu commented on robot/motors.c
> +    GO_FORWARD
un peu de nazisme quand même : tu peux ajouter des () à ton macro et virer le ; pour que ça aie l'air d'une fonction (cf ce que fait Giovanni tout le temps)

2017-01-23 14:07 UTC, AlbandeCrevoisier commented
Je n'ai modifié que coordination.x (et un truc qui appelle une fonction de coordination.c), je pensais que Paul avait déjà merge cette branche dans dev et que ça ne changerait que coordination.c. D'où ma question hier de savoir sur quelle branche mettre coordination.c.

2017-01-23 15:58 UTC, PercevalSA requested changes
Need some coding style change :)

2017-01-23 15:58 UTC, PercevalSA commented on robot/asser.c
> + * the robot
l'alignement à 80 ça devient ridicule ici ! c'est à la limite de l'illisibilité !!

2017-01-23 15:58 UTC, PercevalSA commented on robot/asser.c
> +    angle_error_delta = 0;
pourquoi les variables angle_error_delta et dist_error_delt sont mise 2x à 0 ?

2017-01-23 15:58 UTC, PercevalSA commented on robot/coding_wheels.c
> +}
ça m'a l'air d'être l'init des roues codeuses avec la conf des fonctions de callback lors des ticks ?

2017-01-23 15:58 UTC, PercevalSA commented on robot/coordination.c
> +/* return 1 if x >= 0, -1 otherwise */
les commentaires sur une ligne se font avec //

2017-01-23 15:58 UTC, PercevalSA commented on robot/coordination.c
> +
il serait sage d'aligner tous les commentaires en fin de lignes et d'utiliser // à la place de /* plop */

2017-01-23 15:58 UTC, PercevalSA commented on robot/coordination.c
> +		t = -1;
il n'ya pas de cohérence dans l'utilisation des crochets pour les if, merci de normaliser tout ça en if(foo) { bar } else { plop }

2017-01-23 15:58 UTC, PercevalSA commented on robot/main.c
> +    start_asservs();
l'alignement n'est pas le même

2017-01-23 15:58 UTC, PercevalSA commented on tests/moving/Makefile
> +	USE_OPT = -O2 -ggdb -fomit-frame-pointer -falign-functions=16 -lm
-lm va dans la macro LDOPT :)

2017-01-23 15:58 UTC, PercevalSA commented on tests/moving/Makefile
> +	   main.c coding_wheels.c usbcfg.c motors.c asser.c moving.c position.c \
pourrais tu utiliser une macro pour les fonction relative aux moteurs du style :
MOTORS = coding_wheels.c motors.c asser.c moving.c position.c
et ajouter $(MOTORS) au CSRC 
?

2017-01-23 15:58 UTC, PercevalSA commented on tests/moving/asser.c
> +    angle_error_delta = 0;
idem angle_error_delta reset 2 fois ?

2017-01-23 15:58 UTC, PercevalSA commented on tests/moving/motors.h
> +    palClearPad(GPIOC,GPIOC_SWITCH_TAMPER);
tu pourras utiliser les fonctions "line" lors du port vers robot :)

2017-01-23 15:58 UTC, PercevalSA commented on tests/moving/moving.c
> +            chprintf(COUT, "##########################\r\n");
"########" -> useless print

2017-01-23 22:53 UTC, AlbandeCrevoisier commented on robot/coordination.c
> +/* return 1 if x >= 0, -1 otherwise */
Il n'y a toujours aucun coding style de spécifié, si tu veux qu'on suive ces règles, il faut les documenter. Typiquement le CS Linux dit l'inverse, je m'étais appuyé dessus.

2017-01-24 09:46 UTC, paulGWF commented on robot/coding_wheels.c
> +}
j'ai viré le fichier, il était inutile en fait

2017-01-24 09:47 UTC, paulGWF commented on robot/exticonf.c
> +
j'ai viré le .c le point h on peut le garder

2017-01-24 09:47 UTC, paulGWF commented on robot/motors.c
> +    GO_FORWARD
c'est en cours

2017-01-24 09:50 UTC, paulGWF commented on robot/motors.c
> +    GO_FORWARD
fait

2017-01-24 09:51 UTC, paulGWF commented on robot/asser.c
> + * the robot
je ne comprends pas ton commentaire

2017-01-24 10:03 UTC, paulGWF commented on tests/moving/Makefile
> +	   main.c coding_wheels.c usbcfg.c motors.c asser.c moving.c position.c \
merci d'avoir fait ça

2017-01-29 19:10 UTC, closed without merging